import jsPDF from 'jspdf';

interface QuizResult {
    topicName: string;
    topicId: string;
    difficulty: string;
    score: number;
    totalQuestions: number;
    correctAnswers: number;
    timeSpent: string;
    date: string;
    questions?: Array<{
        question: string;
        userAnswer: string;
        correctAnswer: string;
        isCorrect: boolean;
    }>;
}

/**
 * Export quiz results to PDF
 */
export async function exportQuizResultsToPDF(result: QuizResult): Promise<void> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPosition = 20;

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Quiz Results', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // Topic Info
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`Topic: ${result.topicName}`, margin, yPosition);
    yPosition += 10;

    doc.setFontSize(12);
    doc.text(`Difficulty: ${result.difficulty}`, margin, yPosition);
    yPosition += 7;
    doc.text(`Date: ${result.date}`, margin, yPosition);
    yPosition += 7;
    doc.text(`Time Spent: ${result.timeSpent}`, margin, yPosition);
    yPosition += 15;

    // Score Section
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Score Summary', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Score: ${result.score}%`, margin, yPosition);
    yPosition += 7;
    doc.text(`Correct Answers: ${result.correctAnswers} / ${result.totalQuestions}`, margin, yPosition);
    yPosition += 15;

    // Questions Detail (if available)
    if (result.questions && result.questions.length > 0) {
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text('Question Details', margin, yPosition);
        yPosition += 10;

        result.questions.forEach((q, index) => {
            // Check if we need a new page
            if (yPosition > 250) {
                doc.addPage();
                yPosition = 20;
            }

            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text(`Q${index + 1}: ${q.question}`, margin, yPosition, {
                maxWidth: pageWidth - 2 * margin
            });
            yPosition += 7;

            doc.setFont('helvetica', 'normal');
            if (q.isCorrect) {
                doc.setTextColor(0, 128, 0);
            } else {
                doc.setTextColor(255, 0, 0);
            }
            doc.text(`Your Answer: ${q.userAnswer}`, margin + 5, yPosition);
            yPosition += 6;

            doc.setTextColor(0, 128, 0);
            doc.text(`Correct Answer: ${q.correctAnswer}`, margin + 5, yPosition);
            yPosition += 6;

            doc.setTextColor(0, 0, 0);
            doc.text(q.isCorrect ? '✓ Correct' : '✗ Incorrect', margin + 5, yPosition);
            yPosition += 10;
        });
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Page ${i} of ${pageCount} | Generated by CodeToCareer`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    doc.save(`quiz-results-${result.topicId}-${Date.now()}.pdf`);
}

/**
 * Export user progress report to PDF
 */
export async function exportProgressReportToPDF(data: {
    userName: string;
    totalQuizzes: number;
    averageScore: number;
    topicsCompleted: number;
    recentQuizzes: Array<{
        topicName: string;
        score: number;
        date: string;
    }>;
}): Promise<void> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPosition = 20;

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Progress Report', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // User Info
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`Student: ${data.userName}`, margin, yPosition);
    yPosition += 10;

    doc.setFontSize(12);
    doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, margin, yPosition);
    yPosition += 15;

    // Statistics
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Overall Statistics', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Quizzes Completed: ${data.totalQuizzes}`, margin, yPosition);
    yPosition += 7;
    doc.text(`Average Score: ${data.averageScore.toFixed(1)}%`, margin, yPosition);
    yPosition += 7;
    doc.text(`Topics Completed: ${data.topicsCompleted}`, margin, yPosition);
    yPosition += 15;

    // Recent Quizzes
    if (data.recentQuizzes && data.recentQuizzes.length > 0) {
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text('Recent Quiz Results', margin, yPosition);
        yPosition += 10;

        data.recentQuizzes.forEach((quiz, index) => {
            if (yPosition > 250) {
                doc.addPage();
                yPosition = 20;
            }

            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.text(`${index + 1}. ${quiz.topicName}`, margin, yPosition);
            yPosition += 6;
            doc.text(`   Score: ${quiz.score}% | Date: ${quiz.date}`, margin, yPosition);
            yPosition += 8;
        });
    }

    // Save the PDF
    doc.save(`progress-report-${Date.now()}.pdf`);
}

/**
 * Export practice problem solution to PDF
 */
export async function exportPracticeSolutionToPDF(data: {
    problemTitle: string;
    difficulty: string;
    code: string;
    language: string;
    testResults: Array<{
        passed: boolean;
        input: string;
        output: string;
    }>;
}): Promise<void> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPosition = 20;

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(data.problemTitle, margin, yPosition);
    yPosition += 10;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Difficulty: ${data.difficulty} | Language: ${data.language}`, margin, yPosition);
    yPosition += 15;

    // Code Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Solution Code:', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont('courier', 'normal');
    const codeLines = data.code.split('\n');
    codeLines.forEach(line => {
        if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
        }
        doc.text(line, margin, yPosition);
        yPosition += 5;
    });

    yPosition += 10;

    // Test Results
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Test Results:', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.testResults.forEach((test, index) => {
        if (yPosition > 260) {
            doc.addPage();
            yPosition = 20;
        }

        if (test.passed) {
            doc.setTextColor(0, 128, 0);
        } else {
            doc.setTextColor(255, 0, 0);
        }
        doc.text(`Test ${index + 1}: ${test.passed ? 'PASSED' : 'FAILED'}`, margin, yPosition);
        yPosition += 6;

        doc.setTextColor(0, 0, 0);
        doc.text(`Input: ${test.input}`, margin + 5, yPosition);
        yPosition += 5;
        doc.text(`Output: ${test.output}`, margin + 5, yPosition);
        yPosition += 8;
    });

    // Save the PDF
    doc.save(`solution-${data.problemTitle.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`);
}
